CREATE TABLE USERS(
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      E_MAIL VARCHAR(320) NOT NULL UNIQUE,
      PASSWORD VARCHAR(100) NOT NULL,
      SALT VARCHAR(36) NOT NULL,
      PHOTO VARCHAR(100) NOT NULL,
      CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
