CREATE TABLE CONTACTS
(
    ID         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID    INT NOT NULL,
    CONTACT_ID INT NOT NULL
);

ALTER TABLE CONTACTS
    ADD CONSTRAINT U_USER_CONTACT UNIQUE (USER_ID, CONTACT_ID);
